version: "3.8"
services:
  nginx:
    hostname: dev_proxy_nginx
    container_name: dev_proxy_nginx
    image: nginx:1.18.0
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/entrypoint.sh:/etc/entrypoint.sh
    entrypoint: ["/etc/entrypoint.sh"]
    ports:
      - "80:80"
    networks:
      - consul

networks:
  consul:
    external: true
